//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MySETIapp.rc
//
#define IDC_MYICON                      2
#define IDD_MYSETIAPP_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_MYSETIAPP                   107
#define IDC_MYSETIAPP                   109
#define IDR_MAINFRAME                   128
#define IDD_BITTOOLS_TEXT_STREAM        129
#define IDD_BITTOOLS_HEX_DUMP           130
#define IDD_BITTOOLS_EXTRACT            131
#define IDD_BITTOOLS_DISTANCES          132
#define IDD_BITTOOLS_BITSEQUENCES       133
#define IDD_SETTINGS                    134
#define IDD_IMGTOOLS_EXTRACT            135
#define IDD_BITTOOLS_BINARYIMAGE        136
#define IDD_IMAGE                       137
#define IDD_BITTOOLS_BITSTATS           138
#define IDD_IMGTOOLS_APPEND_END         139
#define IDD_IMGTOOLS_ADD_IMAGES         142
#define IDD_IMGTOOLS_LEFTACCORDION      143
#define IDD_IMGTOOLS_FOLDRIGHT          144
#define IDD_IMGTOOLS_FOLDDOWN           145
#define IDD_IMGTOOLS_FOLDUP             146
#define IDD_IMGTOOLS_RIGHTACCORDION     147
#define IDD_IMGTOOLS_FOLDLEFT           148
#define IDD_IMGTOOLS_LEFTSHIFTROWS      149
#define IDD_IMGTOOLS_REORDER            150
#define IDD_IMGTOOLS_CONVOLUTION        151
#define IDD_IMGTOOLS_APPEND_RIGHT       152
#define IDD_BITTOOLS_REORDER            153
#define IDD_IMGTOOLS_MIRROR             154
#define IDD_IMGTOOLS_ROTATE             155
#define IDD_IMGTOOLS_DECIMATION         156
#define IDD_IMGTOOLS_RESIZE             157
#define IDD_BITTOOLS_TEXT2STREAM        158
#define IDD_IMGTOOLS_ADD_CONSTANT       159
#define IDD_IMGTOOLS_STDDECIMATION      160
#define IDC_CONVERT                     1000
#define IDC_ABOUT_AUTHOR                1001
#define IDC_XSIZE                       1001
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_SKIP_BITS                   1002
#define IDC_YSIZE                       1002
#define IDC_XSIZE2                      1002
#define IDC_ABOUT_NAME                  1003
#define IDC_COPY_BITS                   1003
#define IDC_NUM_FRAMES                  1003
#define IDC_ABOUT_COPYRIGHT             1004
#define IDC_EXTRACT                     1004
#define IDC_XSIZEI2                     1004
#define IDC_XSIZE3                      1004
#define IDC_PIXEL_SIZE                  1004
#define IDC_REPORT                      1005
#define IDC_YSIZEI2                     1005
#define IDC_APPEND                      1006
#define IDC_NUM_FRAMES2                 1006
#define IDC_TEXT_OUTPUT                 1007
#define IDC_ADD                         1007
#define IDC_ADD2                        1008
#define IDC_SUBTRACT                    1008
#define IDC_BLOCK_BITS                  1011
#define IDC_XSIZEI                      1012
#define IDC_BLOCK_NUM                   1013
#define IDC_YSIZEI                      1013
#define IDC_BIT_DEPTH                   1014
#define IDC_XLOC                        1014
#define IDC_PIXEL_SIZEI                 1014
#define IDC_YLOC                        1015
#define IDC_CENTERED                    1016
#define IDC_FOLD                        1017
#define IDC_END_FRAME                   1017
#define IDC_TEXT_INPUT                  1018
#define IDC_START_FRAME                 1018
#define IDC_CONVOLVE                    1019
#define IDC_INCR_FRAMES                 1020
#define IDC_TEXT_INPUT_BROWSE           1021
#define IDC_FOLD_NUMBER                 1022
#define IDC_SHIFT                       1023
#define IDC_SETTINGS_DISPLAY_RESULTS    1024
#define IDC_BMP_RESULTS                 1025
#define IDC_BMP_RESULTS_BROWSE          1026
#define IDC_SETTINGS_AUTOSCALE_RESULTS  1027
#define IDC_MIRROR_HORIZ                1027
#define IDC_MIRROR_VERT                 1028
#define IDC_SETTINGS_RGB_DISPLAY        1029
#define IDC_ROTATE                      1029
#define IDC_SETTINGS_AUTOSIZE           1030
#define IDC_MIRROR                      1030
#define IDC_ROTATE_CCW                  1031
#define IDC_ROTATE_CW                   1032
#define IDC_BINARY_INPUT                1033
#define IDC_DECIMATE                    1033
#define IDC_PROLOGUE_SIZE               1034
#define IDC_RESIZE                      1034
#define IDC_BLOCK_HEADER_BITS           1035
#define IDC_INPUT_BROWSE                1036
#define IDC_TEXT_OUTPUT_BROWSE          1037
#define IDC_IMAGE_INPUT_BROWSE2         1038
#define IDC_BINARY_OUTPUT               1038
#define IDC_BITORDER                    1039
#define IDC_OUTPUT_BROWSE               1039
#define IDC_SCALE_PIXEL                 1040
#define IDC_VALUE                       1040
#define IDC_GENERATE_BMP                1041
#define IDC_BATCH                       1042
#define IDC_XSIZE_END                   1042
#define IDC_XDECIMATE                   1043
#define IDC_YDECIMATE                   1044
#define IDC_INI_FILE                    1045
#define IDC_INI_FILE2                   1046
#define IDC_EXE_FILE                    1046
#define IDC_REORDER                     1074
#define IDC_IMAGE_INPUT_BROWSE          1077
#define IDC_IMAGE_INPUT                 1078
#define IDC_IMAGE_OUTPUT                1079
#define IDC_IMAGE_OUTPUT_BROWSE         1080
#define IDC_IMAGE_INPUT2                1081
#define IDC_IMAGE_CONV_SCALE_BIN        1083
#define IDC_OUTPUT_XSIZE                1094
#define IDC_OUTPUT_YSIZE                1095
#define IDC_EXTRACT_OUTPUT_FILE_BROWSE  1097
#define IDM_BITTOOLS_TEXT_IMAGE         32795
#define IDM_BITTOOLS_HEXDUMP            32796
#define IDM_BITTOOLS_TEXT_STREAM        32797
#define IDM_BITTOOLS_BITDISTANCES       32798
#define IDM_BITTOOLS_BITSEQUENCES       32799
#define IDM_BITTOOLS_BITSTATS           32800
#define IDM_BITTOOLS_CONVERT            32801
#define IDM_BITTOOLS_BINARYIMAGE        32803
#define IDM_BITTOOLS_BITREORDER         32804
#define IDM_IMGTOOLS_PROPERTIES         32805
#define IDM_IMGTOOLS_EXTRACT            32810
#define IDM_FOLDING_FOLDLEFT            32811
#define IDM_FOLDING_FOLDRIGHT           32812
#define IDM_FOLDING_FOLDUP              32813
#define IDM_FOLDING_FOLDDOWN            32814
#define IDM_FOLDING_RIGHTACCORDION      32815
#define IDM_FOLDING_LEFTACCORDION       32816
#define IDM_IMGTOOLS_REORDER            32817
#define IDM_IMGTOOLS_CONVOLUTION        32818
#define IDM_IMGTOOLS_LEFTSHIFTROWS      32819
#define ID_IMAGETOOLS_ADDIMAGES         32820
#define ID_IMAGETOOLS_APPENDIMAGES      32821
#define ID_IMAGETOOLS_APPENDIMAGEONRIGHT 32822
#define IDM_IMGTOOLS_ADDIMAGES          32823
#define IDM_IMGTOOLS_APPENDEND          32824
#define IDM_IMGTOOLS_APPEND_RIGHT       32825
#define IDM_IMGTOOLS_APPEND_END         32826
#define IDM_BITTOOLS_EXTRACT            32827
#define IDM_FILE_TOTXT                  32831
#define IDM_FILE_TOBMP                  32832
#define IDM_PROPERTIES_SETTINGS         32834
#define IDM_SETTINGS                    32835
#define IDC_FILE_OPEN                   32838
#define IDM_IMAGETOOLS_ROTATE           32842
#define IDM_IMAGETOOLS_MIRROR           32844
#define IDM_IMAGETOOLS_DECIMATION       32849
#define IDM_BITTOOLS_DECIMATION         32850
#define IDM_IMAGETOOLS_RESIZE           32853
#define IDM_BITTOOLS_ENCODE             32857
#define IDM_BITTOOLS_DECODER            32858
#define IDM_BITTOOLS_TEXT2BITSTREAM     32861
#define IDM_FILE_IMPORT_BMP             32863
#define IDM_IMPORT_BMP                  32864
#define IDM_FILE_HEX2BINARY             32866
#define IDM_IMPORT_CAMIRA               32868
#define IDM_IMAGE_SUBTRACTCONSTANT      32870
#define IDM_IMGTOOLS_SUBTRACTCONSTANT   32871
#define IDM_SUBTRACT_CONSTANT           32872
#define IDM_ADDSUBTRACT_CONSTANT        32873
#define IDM_IMAGETOOLS_STDECIMATION     32876
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32877
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
