//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MySETIapp.rc
//
#define IDC_MYICON                      2
#define IDD_MYSETIAPP_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_MYSETIAPP                   107
#define IDC_MYSETIAPP                   109
#define IDR_MAINFRAME                   128
#define IDD_BITTOOLS_TEXT_STREAM        129
#define IDD_BITTOOLS_HEX_DUMP           130
#define IDD_BITTOOLS_EXTRACT            131
#define IDD_BITTOOLS_DISTANCES          132
#define IDD_BITTOOLS_BITSEQUENCES       133
#define IDD_SETTINGS                    134
#define IDD_IMGTOOLS_EXTRACT            135
#define IDD_BITTOOLS_BINARYIMAGE        136
#define IDD_IMAGE                       137
#define IDD_BITTOOLS_BITSTATS           138
#define IDD_IMGTOOLS_APPEND_END         139
#define IDD_IMGTOOLS_ADD_IMAGES         142
#define IDD_IMGTOOLS_LEFTACCORDION      143
#define IDD_IMGTOOLS_FOLDRIGHT          144
#define IDD_IMGTOOLS_FOLDDOWN           145
#define IDD_IMGTOOLS_FOLDUP             146
#define IDD_IMGTOOLS_RIGHTACCORDION     147
#define IDD_IMGTOOLS_FOLDLEFT           148
#define IDD_IMGTOOLS_LEFTSHIFTROWS      149
#define IDD_IMGTOOLS_REORDER            150
#define IDD_IMGTOOLS_CONVOLUTION        151
#define IDD_IMGTOOLS_APPEND_RIGHT       152
#define IDD_BITTOOLS_REORDER            153
#define IDD_IMGTOOLS_MIRROR             154
#define IDD_IMGTOOLS_ROTATE             155
#define IDD_IMGTOOLS_DECIMATION         156
#define IDD_IMGTOOLS_RESIZE             157
#define IDD_BITTOOLS_TEXT2STREAM        158
#define IDD_IMGTOOLS_ADD_CONSTANT       159
#define IDD_IMGTOOLS_MATH_CONSTANT      159
#define IDD_IMGTOOLS_STDDECIMATION      160
#define IDD_IMGTOOLS_REPLICATION        161
#define IDD_IMGTOOLS_REORDER_ALG        162
#define IDD_BITTOOLS_EXTRACT_Packets    163
#define IDD_BITTOOLS_EXTRACT_SYMBOLS    163
#define IDD_IMGTOOLS_EXTRACT_SYMBOLS    163
#define IDD_IMGTOOLS_INSERT_IMAGE       164
#define IDD_BITTOOLS_SPP_EXTRACT        165
#define IDD_IMGTOOLS_IMAGE2STREAM       166
#define IDD_BITTOOLS_REMOVENULLS        167
#define IDD_IMGTOOLS_REORDER_BATCH      168
#define IDD_IMGTOOLS_ADD_KERNEL         169
#define IDC_APID                        1060
#define IDC_HEADER2SIZE                 1061
#define IDC_TEXT_OUTPUT2                1062
#define IDC_TEXT_OUTPUT2_BROWSE         1063
#define IDC_STRICT                      1064
#define IDC_SAVE_SUMMARY                1065
#define IDC_WARN                        1066
#define IDC_ADDSUBTRACT                 1067
#define IDC_MULTIPLY                    1068
#define IDC_DIVIDE                      1069
#define IDC_PERFORM                     1070
#define IDC_HEADER                      1072
#define IDC_FRAMES                      1073
#define IDC_REORDER                     1074
#define IDC_NULLVALUE                   1075
#define IDC_BINARY_OUTPUT_BROWSE        1076
#define IDC_IMAGE_INPUT_BROWSE          1077
#define IDC_IMAGE_INPUT                 1078
#define IDC_IMAGE_OUTPUT                1079
#define IDC_IMAGE_OUTPUT_BROWSE         1080
#define IDC_IMAGE_INPUT2                1081
#define IDC_BATCH_INPUT                 1081
#define IDC_BATCH_INPUT_BROWSE          1082
#define IDC_IMAGE_CONV_SCALE_BIN        1083
#define IDC_FILESIZE                    1090
#define IDC_OUTPUT_XSIZE                1094
#define IDC_OUTPUT_YSIZE                1095
#define IDC_EXTRACT_OUTPUT_FILE_BROWSE  1097
#define IDC_CONVERT                     1100
#define IDC_ABOUT_AUTHOR                1101
#define IDC_XSIZE                       1102
#define IDC_ABOUT_LICENSE               1103
#define IDC_ABOUT_VERSION               1104
#define IDC_SKIP_BITS                   1105
#define IDC_YSIZE                       1106
#define IDC_XSIZE2                      1107
#define IDC_ABOUT_NAME                  1108
#define IDC_COPY_BITS                   1109
#define IDC_NUM_FRAMES                  1110
#define IDC_ABOUT_COPYRIGHT             1111
#define IDC_EXTRACT                     1112
#define IDC_XSIZEI2                     1113
#define IDC_XSIZE3                      1114
#define IDC_PIXEL_SIZE                  1115
#define IDC_REPORT                      1116
#define IDC_YSIZEI2                     1117
#define IDC_P1                          1118
#define IDC_APPEND                      1119
#define IDC_YSIZE_SYMBOL                1120
#define IDC_P2                          1121
#define IDC_TEXT_OUTPUT                 1122
#define IDC_ADD                         1123
#define IDC_ADD2                        1124
#define IDC_SUBTRACT                    1125
#define IDC_NUM_FRAMES2                 1126
#define IDC_BLOCK_BITS                  1127
#define IDC_XSIZEI                      1128
#define IDC_BLOCK_NUM                   1129
#define IDC_YSIZEI                      1130
#define IDC_BIT_DEPTH                   1131
#define IDC_XLOC                        1132
#define IDC_PIXEL_SIZEI                 1133
#define IDC_YLOC                        1134
#define IDC_CENTERED                    1135
#define IDC_FOLD                        1136
#define IDC_END_FRAME                   1137
#define IDC_TEXT_INPUT                  1138
#define IDC_START_FRAME                 1139
#define IDC_CONVOLVE                    1140
#define IDC_INCR_FRAMES                 1141
#define IDC_TEXT_INPUT_BROWSE           1142
#define IDC_FOLD_NUMBER                 1143
#define IDC_SHIFT                       1144
#define IDC_SETTINGS_DISPLAY_RESULTS    1145
#define IDC_BMP_RESULTS                 1146
#define IDC_BMP_RESULTS_BROWSE          1147
#define IDC_SETTINGS_AUTOSCALE_RESULTS  1148
#define IDC_MIRROR_HORIZ                1149
#define IDC_SETTINGS_DISPLAY_RESULTS2   1149
#define IDC_SETTINGS_AUTO_PNG           1149
#define IDC_MIRROR_VERT                 1150
#define IDC_IMG_TEMP                    1151
#define IDC_SETTINGS_RGB_DISPLAY        1152
#define IDC_ROTATE                      1153
#define IDC_SETTINGS_AUTOSIZE           1154
#define IDC_MIRROR                      1155
#define IDC_IMG_TEMP_BROWSE             1156
#define IDC_ROTATE_CCW                  1157
#define IDC_ROTATE_CW                   1158
#define IDC_BINARY_INPUT                1159
#define IDC_DECIMATE                    1160
#define IDC_PROLOGUE_SIZE               1161
#define IDC_RESIZE                      1162
#define IDC_BLOCK_HEADER_BITS           1163
#define IDC_INPUT_BROWSE                1164
#define IDC_TEXT_OUTPUT_BROWSE          1165
#define IDC_IMAGE_INPUT_BROWSE2         1166
#define IDC_BINARY_OUTPUT               1167
#define IDC_BITORDER                    1168
#define IDC_OUTPUT_BROWSE               1169
#define IDC_INPUT_BITORDER              1169
#define IDC_SCALE_PIXEL                 1170
#define IDC_VALUE                       1171
#define IDC_GENERATE_BMP                1172
#define IDC_INVERT                      1173
#define IDC_BATCH                       1174
#define IDC_XSIZE_END                   1175
#define IDC_XDECIMATE                   1176
#define IDC_YDECIMATE                   1177
#define IDC_INI_FILE                    1178
#define IDC_EXE_FILE                    1179
#define IDC_XDUPLICATE                  1180
#define IDC_YDUPLICATE                  1181
#define IDC_REPLICATE                   1182
#define IDC_COMBO_ALG                   1183
#define IDC_XSIZE_SYMBOL                1184
#define IDC_SKIP_BYTES                  1185
#define IDC_1D                          1186
#define IDC_2D                          1187
#define IDC_HIGHLIGHT                   1188
#define IDC_OVERWRITE                   1189
#define IDC_P3                          1222
#define IDC_NULL_LENGTH                 1277
#define IDM_BITTOOLS_TEXT_IMAGE         32795
#define IDM_BITTOOLS_HEXDUMP            32796
#define IDM_BITTOOLS_TEXT_STREAM        32797
#define IDM_BITTOOLS_BITDISTANCES       32798
#define IDM_BITTOOLS_BITSEQUENCES       32799
#define IDM_BITTOOLS_BITSTATS           32800
#define IDM_BITTOOLS_CONVERT            32801
#define IDM_BITTOOLS_BINARYIMAGE        32803
#define IDM_BITTOOLS_BITREORDER         32804
#define IDM_IMGTOOLS_PROPERTIES         32805
#define IDM_IMGTOOLS_EXTRACT            32810
#define IDM_FOLDING_FOLDLEFT            32811
#define IDM_FOLDING_FOLDRIGHT           32812
#define IDM_FOLDING_FOLDUP              32813
#define IDM_FOLDING_FOLDDOWN            32814
#define IDM_FOLDING_RIGHTACCORDION      32815
#define IDM_FOLDING_LEFTACCORDION       32816
#define IDM_IMGTOOLS_REORDER            32817
#define IDM_IMGTOOLS_CONVOLUTION        32818
#define IDM_IMGTOOLS_LEFTSHIFTROWS      32819
#define IDM_IMGTOOLS_ADDIMAGES          32823
#define IDM_IMGTOOLS_APPENDEND          32824
#define IDM_IMGTOOLS_APPEND_RIGHT       32825
#define IDM_IMGTOOLS_APPEND_END         32826
#define IDM_BITTOOLS_EXTRACT            32827
#define IDM_FILE_TOTXT                  32831
#define IDM_FILE_TOBMP                  32832
#define IDM_PROPERTIES_SETTINGS         32834
#define IDM_SETTINGS                    32835
#define IDC_FILE_OPEN                   32838
#define IDM_IMAGETOOLS_ROTATE           32842
#define IDM_IMAGETOOLS_MIRROR           32844
#define IDM_IMAGETOOLS_DECIMATION       32849
#define IDM_BITTOOLS_DECIMATION         32850
#define IDM_IMAGETOOLS_RESIZE           32853
#define IDM_BITTOOLS_ENCODE             32857
#define IDM_BITTOOLS_DECODER            32858
#define IDM_BITTOOLS_TEXT2BITSTREAM     32861
#define IDM_FILE_IMPORT_BMP             32863
#define IDM_IMPORT_BMP                  32864
#define IDM_FILE_HEX2BINARY             32866
#define IDM_IMPORT_CAMIRA               32868
#define IDM_IMGTOOLS_SUBTRACTCONSTANT   32871
#define IDM_IMAGETOOLS_STDECIMATION     32876
#define IDM_IMAGETOOLS_REPLICATION      32879
#define IDM_IMAGETOOLS_REORDER_ALG      32882
#define IDM_BITTOOLS_EXTRACT_PACKETS    32884
#define IDM_IMGTOOLS_EXTRACT_PACKETS    32885
#define IDM_IMGTOOLS_INSERT_IMAGE       32887
#define IDM_BITTOOLS_SPP_EXTRACT        32889
#define IDM_MATH_CONSTANT               32890
#define IDM_IMAGETOOLS_EXPORTTEXT       32893
#define IDM_IMAGETOOLS_EXPORTBITSTREAM  32896
#define IDM_BITTOOLS_REMOVENULLS        32898
#define IDM_IMGTOOLS_REORDER_BATCH      32900
#define ID_IMAGETOOLS_ADD               32901
#define IDM_IMGTOOLS_ADD_KERNEL         32902
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32903
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
